add_subdirectory(common)
add_subdirectory(distributed_runtime)
add_subdirectory(framework)
if(USE_MLU)
  add_subdirectory(triton_jit)
endif()
add_subdirectory(kernels)
if(USE_NPU)
  target_link_libraries(parallel_state PUBLIC tilelang_kernels)
endif()
add_subdirectory(layers)
add_subdirectory(platform)
add_subdirectory(runtime)
add_subdirectory(scheduler)
add_subdirectory(util)
