set(CMAKE_MUSA_SOURCE_FILE_EXTENSIONS mu)
if(UNIX)
  set(CMAKE_MUSA_OUTPUT_EXTENSION .o)
else()
  set(CMAKE_MUSA_OUTPUT_EXTENSION .obj)
endif()

set(CMAKE_INCLUDE_FLAG_MUSA "-I")

set(CMAKE_MUSA_COMPILE_OBJECT 
    "<CMAKE_MUSA_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -mtgpu -c <SOURCE> -o <OBJECT>"
)

set(CMAKE_MUSA_LINK_EXECUTABLE 
    "<CMAKE_MUSA_COMPILER> <FLAGS> <LINK_FLAGS> <OBJECTS> -lmusa -lmusart -o <TARGET> <LINK_LIBRARIES>"
)

set(CMAKE_MUSA_INFORMATION_LOADED 1)